resources:
  - name: npm_git_repo
    type: GitRepo
    configuration:
      gitProvider: github
      path: bharath92/jfrog-npm-build-publish
      branches:
        include: main

pipelines:
  - name: npm_build_publish
    steps:
      - name: build_and_publish
        type: Bash
        configuration:
          inputResources:
            - name: npm_git_repo
          integrations:
            - name: artifactory
        execution:
          onExecute:
            - pushd $res_npm_git_repo_resourcePath
            - jfrog rt npm-config --repo-deploy npm-local --server-id-deploy artifactory
            - jfrog rt npm-publish --build-name=$step_name --build-number=$run_number --detailed-summary
