resources:
  - name: npm_git_repo
    type: GitRepo
    configuration:
      gitProvider: github
      path: bharath92/jfrog-npm-build-publish
      branches:
        include: main
  
  - name: build_info
    type: BuildInfo
    configuration:
      sourceArtifactory: artifactory
      buildName: build_and_publish
      buildNumber: -1

pipelines:
  - name: npm_build_publish
    steps:
      - name: jenkins
        type: Jenkins
        configuration:
          jenkinsJobName: testPipeline
          integrations:
            - name: jenkins
      
      - name: build
        type: NpmBuild
        configuration:
          resolverRepo: npm-remote
          inputSteps:
            - name: jenkins
          inputResources:
            - name: npm_git_repo
          integrations:
            - name: artifactory
        execution:
          onStart:
            - pushd $res_npm_git_repo_resourcePath
            - npm version "0.0.$run_number"
            - popd
      
      - name: publish
        type: NpmPublish
        configuration:
          forceXrayScan: true
          failOnScan: true
          autoPublishBuildInfo: true
          deployerRepo: npm-local
          inputSteps:
            - name: build
          integrations:
            - name: artifactory
          outputResources:
             - name: build_info
      
      - name: demo
        type: Bash
        configuration:
          inputResources:
            - name: npm_git_repo
          inputSteps:
            - name: publish
        execution:
          onExecute:
            - echo foo
            - pushd $res_npm_git_repo_resourcePath
            - node index.js
